launch: linked_list.c
	gcc linked_list.c -o linked_list
	./linked_list

launch_reverse_linked_list: reversing_linked_list.c
			    gcc reversing_linked_list.c -o reversing_linked_list
			    ./reversing_linked_list
