launch-c11: linked_list.c
	gcc -std=c11 linked_list.c -o linked_list
	./linked_list

launch_ll: linked_list.c
	gcc linked_list.c -o linked_list
	./linked_list

launch_fp: function_pointers.c
	gcc function_pointers.c -o function_pointers
	./function_pointers
